import { Kader, Surat, Arsip, Kaderisasi, Agenda, Berita, StatsDashboard, Notifikasi, Inventaris, AuditLog } from '@/types';

export const mockStats: StatsDashboard = {
  totalKader: 1247,
  totalKomisariat: 12,
  totalRayon: 48,
  suratMasuk: 34,
  suratKeluar: 28,
  arsipAktif: 312,
  arsipTahunIni: 87,
  agendaTerdekat: 5,
  pengajuanSurat: 8,
  notifikasiBaru: 12,
};

export const mockKader: Kader[] = [
  {
    id: '1',
    foto: 'https://ui-avatars.com/api/?name=Ahmad+Fauzi&background=007A33&color=fff',
    nama: 'Ahmad Fauzi',
    nik: '3204010101990001',
    nim: '2019310001',
    tempatLahir: 'Bandung',
    tanggalLahir: '1999-01-01',
    jenisKelamin: 'L',
    alamat: 'Jl. Soekarno Hatta No. 1, Bandung',
    email: 'ahmad.fauzi@email.com',
    noHp: '081234567890',
    komisariat: 'Komisariat UNPAD',
    rayon: 'Rayon Hukum',
    statusKeanggotaan: 'aktif',
    statusAktif: true,
    jenjangKaderisasi: 'PKL',
    statusKTA: 'aktif',
    nomorKTA: 'KTA-2024-001',
    riwayatJabatan: [
      { id: '1', jabatan: 'Ketua Rayon', organisasi: 'Rayon Hukum', periode: '2022-2023' },
      { id: '2', jabatan: 'Wakil Sekretaris', organisasi: 'Komisariat UNPAD', periode: '2023-2024' },
    ],
    riwayatPelatihan: [
      { id: '1', nama: 'MAPABA Angkatan XII', tahun: '2019', keterangan: 'Lulus' },
      { id: '2', nama: 'PKD Angkatan V', tahun: '2020', keterangan: 'Lulus' },
      { id: '3', nama: 'PKL Angkatan II', tahun: '2022', keterangan: 'Lulus' },
    ],
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: '2',
    foto: 'https://ui-avatars.com/api/?name=Siti+Rahayu&background=F4B400&color=fff',
    nama: 'Siti Rahayu',
    nik: '3204010201000002',
    nim: '2020310002',
    tempatLahir: 'Soreang',
    tanggalLahir: '2000-02-15',
    jenisKelamin: 'P',
    alamat: 'Jl. Kopo No. 45, Bandung',
    email: 'siti.rahayu@email.com',
    noHp: '082345678901',
    komisariat: 'Komisariat STISIP',
    rayon: 'Rayon Sosial',
    statusKeanggotaan: 'aktif',
    statusAktif: true,
    jenjangKaderisasi: 'PKD',
    statusKTA: 'aktif',
    nomorKTA: 'KTA-2024-002',
    riwayatJabatan: [
      { id: '1', jabatan: 'Bendahara Rayon', organisasi: 'Rayon Sosial', periode: '2022-2023' },
    ],
    riwayatPelatihan: [
      { id: '1', nama: 'MAPABA Angkatan XIII', tahun: '2020', keterangan: 'Lulus' },
      { id: '2', nama: 'PKD Angkatan VI', tahun: '2021', keterangan: 'Lulus' },
    ],
    createdAt: '2024-01-05',
    updatedAt: '2024-06-10',
  },
  {
    id: '3',
    foto: 'https://ui-avatars.com/api/?name=Muhammad+Rizky&background=007A33&color=fff',
    nama: 'Muhammad Rizky',
    nik: '3204010301010003',
    nim: '2021310003',
    tempatLahir: 'Cimahi',
    tanggalLahir: '2001-03-20',
    jenisKelamin: 'L',
    alamat: 'Jl. Cihampelas No. 12, Cimahi',
    email: 'm.rizky@email.com',
    noHp: '083456789012',
    komisariat: 'Komisariat UNJANI',
    rayon: 'Rayon Teknik',
    statusKeanggotaan: 'aktif',
    statusAktif: true,
    jenjangKaderisasi: 'MAPABA',
    statusKTA: 'belum',
    riwayatJabatan: [],
    riwayatPelatihan: [
      { id: '1', nama: 'MAPABA Angkatan XIV', tahun: '2021', keterangan: 'Lulus' },
    ],
    createdAt: '2024-02-01',
    updatedAt: '2024-06-15',
  },
  {
    id: '4',
    foto: 'https://ui-avatars.com/api/?name=Nur+Fadilah&background=F4B400&color=fff',
    nama: 'Nur Fadilah',
    nik: '3204010401020004',
    nim: '2022310004',
    tempatLahir: 'Banjaran',
    tanggalLahir: '2002-04-10',
    jenisKelamin: 'P',
    alamat: 'Jl. Banjaran Raya No. 8, Bandung',
    email: 'nur.fadilah@email.com',
    noHp: '084567890123',
    komisariat: 'Komisariat UIN',
    rayon: 'Rayon Tarbiyah',
    statusKeanggotaan: 'aktif',
    statusAktif: true,
    jenjangKaderisasi: 'PKD',
    statusKTA: 'aktif',
    nomorKTA: 'KTA-2024-003',
    riwayatJabatan: [
      { id: '1', jabatan: 'Sekretaris Rayon', organisasi: 'Rayon Tarbiyah', periode: '2023-2024' },
    ],
    riwayatPelatihan: [
      { id: '1', nama: 'MAPABA Angkatan XV', tahun: '2022', keterangan: 'Lulus' },
      { id: '2', nama: 'PKD Angkatan VII', tahun: '2023', keterangan: 'Lulus' },
    ],
    createdAt: '2024-02-15',
    updatedAt: '2024-07-01',
  },
  {
    id: '5',
    foto: 'https://ui-avatars.com/api/?name=Deni+Kurniawan&background=007A33&color=fff',
    nama: 'Deni Kurniawan',
    nik: '3204010501030005',
    nim: '2018310005',
    tempatLahir: 'Majalaya',
    tanggalLahir: '1998-05-25',
    jenisKelamin: 'L',
    alamat: 'Jl. Majalaya No. 23, Bandung',
    email: 'deni.k@email.com',
    noHp: '085678901234',
    komisariat: 'Komisariat STTB',
    rayon: 'Rayon Ekonomi',
    statusKeanggotaan: 'alumni',
    statusAktif: false,
    jenjangKaderisasi: 'PKL',
    statusKTA: 'expired',
    nomorKTA: 'KTA-2020-015',
    riwayatJabatan: [
      { id: '1', jabatan: 'Ketua Komisariat', organisasi: 'Komisariat STTB', periode: '2021-2022' },
      { id: '2', jabatan: 'Wakil Ketua Cabang', organisasi: 'PC PMII Kab. Bandung', periode: '2022-2023' },
    ],
    riwayatPelatihan: [
      { id: '1', nama: 'MAPABA Angkatan X', tahun: '2018', keterangan: 'Lulus' },
      { id: '2', nama: 'PKD Angkatan IV', tahun: '2019', keterangan: 'Lulus' },
      { id: '3', nama: 'PKL Angkatan I', tahun: '2021', keterangan: 'Lulus' },
    ],
    createdAt: '2023-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: '6',
    foto: 'https://ui-avatars.com/api/?name=Rini+Anggraeni&background=6366f1&color=fff',
    nama: 'Rini Anggraeni',
    nik: '3204010601040006',
    nim: '2023310006',
    tempatLahir: 'Ciparay',
    tanggalLahir: '2003-06-15',
    jenisKelamin: 'P',
    alamat: 'Jl. Ciparay No. 5, Bandung',
    email: 'rini.a@email.com',
    noHp: '086789012345',
    komisariat: 'Komisariat Unpas',
    rayon: 'Rayon Komunikasi',
    statusKeanggotaan: 'aktif',
    statusAktif: true,
    jenjangKaderisasi: 'MAPABA',
    statusKTA: 'belum',
    riwayatJabatan: [],
    riwayatPelatihan: [
      { id: '1', nama: 'MAPABA Angkatan XVI', tahun: '2023', keterangan: 'Lulus' },
    ],
    createdAt: '2024-03-10',
    updatedAt: '2024-07-05',
  },
];

export const mockSurat: Surat[] = [
  {
    id: '1',
    nomorSurat: '001/PC-PMII-KBD/VII/2026',
    perihal: 'Undangan Rapat Koordinasi Pengurus',
    jenis: 'keluar',
    tanggal: '2026-07-10',
    penerima: 'Seluruh Pengurus Komisariat',
    status: 'disetujui',
    keterangan: 'Rapat koordinasi bulanan pengurus',
    qrCode: 'ESAH-2026-001',
    createdBy: 'Sekretaris',
    createdAt: '2026-07-10',
    riwayat: [
      { id: '1', aksi: 'Dibuat', oleh: 'Sekretaris', tanggal: '2026-07-10', keterangan: 'Draft surat dibuat' },
      { id: '2', aksi: 'Disetujui', oleh: 'Ketua', tanggal: '2026-07-11', keterangan: 'Surat disetujui dan ditandatangani' },
    ],
  },
  {
    id: '2',
    nomorSurat: '002/PC-PMII-KBD/VII/2026',
    perihal: 'Permohonan Izin Penggunaan Aula',
    jenis: 'keluar',
    tanggal: '2026-07-08',
    penerima: 'Kepala Dinas Pemuda dan Olahraga Kab. Bandung',
    status: 'selesai',
    keterangan: 'Permohonan tempat untuk PKD',
    qrCode: 'ESAH-2026-002',
    createdBy: 'Sekretaris',
    createdAt: '2026-07-08',
    riwayat: [
      { id: '1', aksi: 'Dibuat', oleh: 'Sekretaris', tanggal: '2026-07-08' },
      { id: '2', aksi: 'Disetujui', oleh: 'Ketua', tanggal: '2026-07-09' },
      { id: '3', aksi: 'Dikirim', oleh: 'Sekretaris', tanggal: '2026-07-09' },
    ],
  },
  {
    id: '3',
    nomorSurat: 'EXT-2026-045',
    perihal: 'Undangan Halaqoh Nasional PMII',
    jenis: 'masuk',
    tanggal: '2026-07-05',
    pengirim: 'PB PMII Jakarta',
    status: 'diproses',
    keterangan: 'Undangan menghadiri halaqoh nasional',
    createdBy: 'Admin',
    createdAt: '2026-07-05',
    riwayat: [
      { id: '1', aksi: 'Diterima', oleh: 'Admin', tanggal: '2026-07-05' },
      { id: '2', aksi: 'Disposisi', oleh: 'Sekretaris', tanggal: '2026-07-06', keterangan: 'Diserahkan ke Ketua untuk tindak lanjut' },
    ],
  },
  {
    id: '4',
    nomorSurat: '003/PC-PMII-KBD/VII/2026',
    perihal: 'Rekomendasi Kader untuk Kegiatan Nasional',
    jenis: 'keluar',
    tanggal: '2026-07-12',
    penerima: 'PB PMII Jakarta',
    status: 'draft',
    createdBy: 'Sekretaris',
    createdAt: '2026-07-12',
    riwayat: [
      { id: '1', aksi: 'Dibuat', oleh: 'Sekretaris', tanggal: '2026-07-12' },
    ],
  },
  {
    id: '5',
    nomorSurat: 'EXT-2026-032',
    perihal: 'Surat Kerjasama Program Mahasiswa',
    jenis: 'masuk',
    tanggal: '2026-06-28',
    pengirim: 'Pemkab Bandung',
    status: 'selesai',
    createdBy: 'Admin',
    createdAt: '2026-06-28',
    riwayat: [
      { id: '1', aksi: 'Diterima', oleh: 'Admin', tanggal: '2026-06-28' },
      { id: '2', aksi: 'Dibalas', oleh: 'Sekretaris', tanggal: '2026-07-01' },
    ],
  },
];

export const mockArsip: Arsip[] = [
  { id: '1', nama: 'SK Kepengurusan PC PMII Kab. Bandung 2024-2026', kategori: 'SK', tahun: '2024', tags: ['kepengurusan', 'resmi'], ukuran: '2.4 MB', format: 'PDF', uploadedBy: 'Admin', createdAt: '2024-01-15', versi: 1, deskripsi: 'Surat Keputusan kepengurusan periode 2024-2026' },
  { id: '2', nama: 'LPJ Rapat Kerja 2025', kategori: 'LPJ', tahun: '2025', tags: ['lpj', 'raker', 'tahunan'], ukuran: '5.1 MB', format: 'PDF', uploadedBy: 'Sekretaris', createdAt: '2025-12-20', versi: 2, deskripsi: 'Laporan pertanggungjawaban rapat kerja tahunan' },
  { id: '3', nama: 'Proposal PKD Angkatan VIII', kategori: 'Proposal', tahun: '2026', tags: ['pkd', 'kaderisasi'], ukuran: '1.8 MB', format: 'PDF', uploadedBy: 'Sekretaris', createdAt: '2026-03-10', versi: 1 },
  { id: '4', nama: 'MoU dengan Pemkab Bandung', kategori: 'MoU', tahun: '2025', tags: ['mou', 'kerjasama'], ukuran: '890 KB', format: 'PDF', uploadedBy: 'Ketua', createdAt: '2025-06-15', versi: 1 },
  { id: '5', nama: 'Dokumentasi MAPABA XV', kategori: 'Foto', tahun: '2022', tags: ['mapaba', 'foto', 'kaderisasi'], ukuran: '48 MB', format: 'ZIP', uploadedBy: 'Admin', createdAt: '2022-10-20', versi: 1 },
  { id: '6', nama: 'AD/ART PMII Terbaru', kategori: 'Dokumen', tahun: '2024', tags: ['adart', 'konstitusi'], ukuran: '3.2 MB', format: 'PDF', uploadedBy: 'Admin', createdAt: '2024-02-01', versi: 3 },
  { id: '7', nama: 'Notulen Rapat Koordinasi Juli 2026', kategori: 'Surat', tahun: '2026', tags: ['notulen', 'rapat'], ukuran: '450 KB', format: 'PDF', uploadedBy: 'Sekretaris', createdAt: '2026-07-05', versi: 1 },
];

export const mockKaderisasi: Kaderisasi[] = [
  { id: '1', jenis: 'MAPABA', angkatan: 'XVI', tanggalMulai: '2026-08-15', tanggalSelesai: '2026-08-17', lokasi: 'Pondok Pesantren Al-Hikmah, Soreang', status: 'open', peserta: 45, lulusCount: 0, komisariat: 'Komisariat UIN', deskripsi: 'MAPABA Angkatan XVI untuk penerimaan anggota baru' },
  { id: '2', jenis: 'PKD', angkatan: 'VIII', tanggalMulai: '2026-09-01', tanggalSelesai: '2026-09-03', lokasi: 'Villa Lembang, Bandung Barat', status: 'open', peserta: 30, lulusCount: 0, deskripsi: 'PKD untuk peningkatan kapasitas kader' },
  { id: '3', jenis: 'MAPABA', angkatan: 'XV', tanggalMulai: '2025-10-10', tanggalSelesai: '2025-10-12', lokasi: 'Kp. Ciwidey, Bandung Selatan', status: 'selesai', peserta: 52, lulusCount: 48, komisariat: 'Komisariat STISIP' },
  { id: '4', jenis: 'PKL', angkatan: 'III', tanggalMulai: '2025-07-20', tanggalSelesai: '2025-07-23', lokasi: 'Gedung Serbaguna PC PMII', status: 'selesai', peserta: 18, lulusCount: 16 },
];

export const mockAgenda: Agenda[] = [
  { id: '1', judul: 'Rapat Koordinasi Pengurus Bulanan', kategori: 'Rapat', tanggal: '2026-07-15', waktu: '19:00', lokasi: 'Sekretariat PC PMII, Soreang', deskripsi: 'Rapat koordinasi rutin bulanan pengurus cabang', penyelenggara: 'PC PMII Kab. Bandung', status: 'upcoming' },
  { id: '2', judul: 'Diskusi Publik: Peran Mahasiswa dalam Pembangunan Daerah', kategori: 'Diskusi', tanggal: '2026-07-18', waktu: '09:00', lokasi: 'Aula UNPAD Jatinangor', penyelenggara: 'PC PMII Kab. Bandung', status: 'upcoming' },
  { id: '3', judul: 'Seminar Kepemimpinan Nasional', kategori: 'Seminar', tanggal: '2026-07-22', waktu: '08:00', lokasi: 'Hotel Santika Bandung', penyelenggara: 'PW PMII Jawa Barat', status: 'upcoming' },
  { id: '4', judul: 'MAPABA Angkatan XVI - Rapat Persiapan', kategori: 'Pelatihan', tanggal: '2026-08-10', waktu: '10:00', lokasi: 'Sekretariat PC PMII', penyelenggara: 'Dept. Kaderisasi', status: 'upcoming' },
  { id: '5', judul: 'Halaqoh Ideologi PMII', kategori: 'Diskusi', tanggal: '2026-07-28', waktu: '15:00', lokasi: 'Sekretariat PC PMII', penyelenggara: 'Dept. Kajian & Ideologi', status: 'upcoming' },
  { id: '6', judul: 'Rapat Kerja Tahunan 2025', kategori: 'Rapat', tanggal: '2025-12-15', waktu: '08:00', lokasi: 'Hotel Horison Bandung', penyelenggara: 'PC PMII Kab. Bandung', status: 'selesai' },
];

export const mockBerita: Berita[] = [
  {
    id: '1',
    judul: 'PC PMII Kabupaten Bandung Luncurkan Sistem Digital E-SAHABAT',
    slug: 'pc-pmii-luncurkan-e-sahabat',
    konten: 'PC PMII Kabupaten Bandung resmi meluncurkan sistem administrasi digital E-SAHABAT sebagai langkah transformasi digital organisasi. Sistem ini mengintegrasikan seluruh administrasi, arsip digital, dan database kader dalam satu platform berbasis web.',
    ringkasan: 'PC PMII Kabupaten Bandung resmi meluncurkan sistem administrasi digital E-SAHABAT sebagai langkah transformasi digital organisasi.',
    thumbnail: 'https://picsum.photos/seed/berita1/800/450',
    kategori: 'Organisasi',
    tags: ['digital', 'transformasi', 'administrasi'],
    penulis: 'Admin E-SAHABAT',
    featured: true,
    publishedAt: '2026-07-12',
    viewCount: 342,
  },
  {
    id: '2',
    judul: 'PKD Angkatan VIII Segera Dibuka, Daftarkan Dirimu!',
    slug: 'pkd-angkatan-viii-dibuka',
    konten: 'Dalam rangka peningkatan kualitas kader, PC PMII Kabupaten Bandung akan menggelar PKD Angkatan VIII pada September 2026.',
    ringkasan: 'PC PMII Kabupaten Bandung membuka pendaftaran PKD Angkatan VIII yang akan dilaksanakan pada September 2026.',
    thumbnail: 'https://picsum.photos/seed/berita2/800/450',
    kategori: 'Kaderisasi',
    tags: ['pkd', 'kaderisasi', 'pendaftaran'],
    penulis: 'Dept. Kaderisasi',
    featured: false,
    publishedAt: '2026-07-10',
    viewCount: 218,
  },
  {
    id: '3',
    judul: 'Diskusi Publik: PMII dan Isu Lingkungan Hidup di Kabupaten Bandung',
    slug: 'diskusi-pmii-lingkungan',
    konten: 'Menyoroti isu lingkungan hidup yang semakin kritis di Kabupaten Bandung, PMII menggelar diskusi publik.',
    ringkasan: 'PMII Kabupaten Bandung menggelar diskusi publik membahas persoalan lingkungan hidup dan peran mahasiswa.',
    thumbnail: 'https://picsum.photos/seed/berita3/800/450',
    kategori: 'Kegiatan',
    tags: ['diskusi', 'lingkungan', 'sosial'],
    penulis: 'Dept. Kajian',
    featured: false,
    publishedAt: '2026-07-05',
    viewCount: 156,
  },
  {
    id: '4',
    judul: 'PMII Kab. Bandung Raih Penghargaan Organisasi Terbaik se-Jawa Barat',
    slug: 'pmii-raih-penghargaan',
    konten: 'Sebuah prestasi membanggakan diraih oleh PC PMII Kabupaten Bandung dalam ajang penghargaan organisasi mahasiswa terbaik.',
    ringkasan: 'PC PMII Kabupaten Bandung berhasil meraih penghargaan organisasi mahasiswa terbaik tingkat Jawa Barat.',
    thumbnail: 'https://picsum.photos/seed/berita4/800/450',
    kategori: 'Prestasi',
    tags: ['penghargaan', 'prestasi', 'jawa barat'],
    penulis: 'Humas PC PMII',
    featured: true,
    publishedAt: '2026-06-28',
    viewCount: 489,
  },
];

export const mockNotifikasi: Notifikasi[] = [
  { id: '1', judul: 'Pengajuan Surat Baru', pesan: 'Ahmad Fauzi mengajukan surat keterangan aktif', jenis: 'info', dibaca: false, createdAt: '2026-07-12T10:30:00', link: '/dashboard/surat' },
  { id: '2', judul: 'Surat Disetujui', pesan: 'Surat 001/PC-PMII-KBD/VII/2026 telah disetujui', jenis: 'success', dibaca: false, createdAt: '2026-07-11T14:20:00', link: '/dashboard/surat' },
  { id: '3', judul: 'Agenda Besok', pesan: 'Rapat Koordinasi Pengurus besok pukul 19:00', jenis: 'warning', dibaca: true, createdAt: '2026-07-11T08:00:00', link: '/dashboard/agenda' },
  { id: '4', judul: 'Anggota Baru Mendaftar', pesan: '3 anggota baru mendaftar dan menunggu verifikasi', jenis: 'info', dibaca: true, createdAt: '2026-07-10T16:45:00', link: '/dashboard/kader' },
  { id: '5', judul: 'Backup Berhasil', pesan: 'Backup database otomatis berhasil dilakukan', jenis: 'success', dibaca: true, createdAt: '2026-07-10T00:01:00' },
];

export const mockInventaris: Inventaris[] = [
  { id: '1', nama: 'Laptop ASUS VivoBook', kode: 'INV-001', lokasi: 'Sekretariat', jumlah: 2, kondisi: 'baik', status: 'tersedia' },
  { id: '2', nama: 'Proyektor Epson', kode: 'INV-002', lokasi: 'Ruang Rapat', jumlah: 1, kondisi: 'baik', status: 'dipinjam', keterangan: 'Dipinjam oleh Komisariat UIN' },
  { id: '3', nama: 'Meja Lipat', kode: 'INV-003', lokasi: 'Gudang', jumlah: 10, kondisi: 'baik', status: 'tersedia' },
  { id: '4', nama: 'Kursi Lipat', kode: 'INV-004', lokasi: 'Gudang', jumlah: 50, kondisi: 'rusak_ringan', status: 'tersedia', keterangan: '5 unit dalam perbaikan' },
  { id: '5', nama: 'Sound System', kode: 'INV-005', lokasi: 'Sekretariat', jumlah: 1, kondisi: 'baik', status: 'tersedia' },
];

export const mockAuditLog: AuditLog[] = [
  { id: '1', user: 'Ahmad Fauzi', aksi: 'LOGIN', modul: 'Auth', detail: 'Login berhasil', ip: '192.168.1.1', timestamp: '2026-07-12T10:00:00' },
  { id: '2', user: 'Sekretaris', aksi: 'CREATE', modul: 'Surat', detail: 'Membuat surat 003/PC-PMII-KBD/VII/2026', ip: '192.168.1.2', timestamp: '2026-07-12T09:45:00' },
  { id: '3', user: 'Admin', aksi: 'UPDATE', modul: 'Kader', detail: 'Memperbarui data kader Ahmad Fauzi', ip: '192.168.1.3', timestamp: '2026-07-11T15:30:00' },
  { id: '4', user: 'Ketua', aksi: 'APPROVE', modul: 'Surat', detail: 'Menyetujui surat 001/PC-PMII-KBD/VII/2026', ip: '192.168.1.4', timestamp: '2026-07-11T14:20:00' },
  { id: '5', user: 'Admin', aksi: 'UPLOAD', modul: 'Arsip', detail: 'Upload SK Kepengurusan 2024', ip: '192.168.1.5', timestamp: '2026-07-10T11:00:00' },
];

export const chartDataPertumbuhan = [
  { bulan: 'Jan', kader: 980 },
  { bulan: 'Feb', kader: 1020 },
  { bulan: 'Mar', kader: 1080 },
  { bulan: 'Apr', kader: 1100 },
  { bulan: 'Mei', kader: 1150 },
  { bulan: 'Jun', kader: 1200 },
  { bulan: 'Jul', kader: 1247 },
];

export const chartDataSurat = [
  { name: 'Masuk', value: 34, fill: '#007A33' },
  { name: 'Keluar', value: 28, fill: '#F4B400' },
  { name: 'Draft', value: 8, fill: '#9ca3af' },
];

export const chartDataKaderisasi = [
  { jenis: 'MAPABA', peserta: 52, lulus: 48 },
  { jenis: 'PKD', peserta: 30, lulus: 27 },
  { jenis: 'PKL', peserta: 18, lulus: 16 },
];

export const komisariatList = [
  'Komisariat UNPAD',
  'Komisariat UIN Sunan Gunung Djati',
  'Komisariat UNJANI',
  'Komisariat STISIP',
  'Komisariat STTB',
  'Komisariat Unpas',
  'Komisariat STAI',
  'Komisariat STIMIK',
  'Komisariat STT Terpadu',
  'Komisariat UPI',
  'Komisariat IKIP Siliwangi',
  'Komisariat UMB',
];

export const rayonList = [
  'Rayon Hukum', 'Rayon Sosial', 'Rayon Teknik', 'Rayon Ekonomi',
  'Rayon Tarbiyah', 'Rayon Pertanian', 'Rayon Kesehatan', 'Rayon Sains',
  'Rayon Komunikasi', 'Rayon Psikologi',
];

export const mockUsers = [
  { id: '1', name: 'Super Admin', email: 'superadmin@esahabat.id', role: 'super_admin', avatar: 'https://ui-avatars.com/api/?name=Super+Admin&background=007A33&color=fff', jabatan: 'Super Administrator' },
  { id: '2', name: 'Ahmad Fauzi', email: 'admin@esahabat.id', role: 'admin', avatar: 'https://ui-avatars.com/api/?name=Ahmad+Fauzi&background=007A33&color=fff', jabatan: 'Administrator' },
  { id: '3', name: 'Siti Rahayu', email: 'sekretaris@esahabat.id', role: 'sekretaris', avatar: 'https://ui-avatars.com/api/?name=Siti+Rahayu&background=F4B400&color=fff', jabatan: 'Sekretaris Umum' },
  { id: '4', name: 'H. Ridwan Kamil', email: 'ketua@esahabat.id', role: 'ketua', avatar: 'https://ui-avatars.com/api/?name=Ridwan+Kamil&background=007A33&color=fff', jabatan: 'Ketua Umum' },
  { id: '5', name: 'Muhammad Rizky', email: 'anggota@esahabat.id', role: 'anggota', avatar: 'https://ui-avatars.com/api/?name=Muhammad+Rizky&background=6366f1&color=fff', jabatan: 'Anggota' },
];
